-- Table: exercises
CREATE TABLE exercises (
    version INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(200) NOT NULL PRIMARY KEY
);

-- Table: logs
CREATE TABLE logs (
    version INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL
);

-- Table: sets
CREATE TABLE sets (
    reps INTEGER NOT NULL CHECK (reps >= 1),
    version INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table: trained_exercises
CREATE TABLE trained_exercises (
    version INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    log_id UUID,
    exercise_name VARCHAR(200),
    FOREIGN KEY (log_id) REFERENCES logs(id),
    FOREIGN KEY (exercise_name) REFERENCES exercises(name)
);

-- Table: trained_exercises_sets
CREATE TABLE trained_exercises_sets (
    sets_id BIGINT NOT NULL,
    trained_exercise_id BIGINT NOT NULL,
    UNIQUE (sets_id),
    FOREIGN KEY (sets_id) REFERENCES sets(id),
    FOREIGN KEY (trained_exercise_id) REFERENCES trained_exercises(id)
);
